/**
 * Google Cloud Text-to-Speech voice catalog.
 *
 * This is the catalog the audio gen picker shows by default. We curated
 * ~16 voices from Google's Studio / Neural2 / WaveNet families — the
 * tiers Freepik uses too — covering male/female × English (US/UK) and
 * Thai. Studio voices are highest quality (and ~10x more expensive),
 * Neural2 is the workhorse mid-tier, WaveNet is the budget option.
 *
 * Naming convention is Google's own: `<lang>-<region>-<family>-<id>`
 *   en-US-Studio-O   →  US English, Studio family, voice "O"
 *   en-US-Neural2-F  →  US English, Neural2 family, voice "F"
 *
 * Source for voice names + characteristics:
 *   https://cloud.google.com/text-to-speech/docs/voices
 *
 * Preview MP3 strategy:
 *   On first load the dialog renders the static `previewUrl` field
 *   below, which points at Supabase Storage at
 *     `voice-previews/google/<voice-id>.mp3`
 *   Pre-generated by `scripts/generate-voice-previews.ts` (run once
 *   per voice catalog change). The bucket is public-read so the
 *   browser can fetch them without an auth token. If the file 404s
 *   (e.g. before the script has been run on a fresh project) the
 *   dialog falls back to a silent "preview unavailable" state — no
 *   crash. See `previewBaseUrl` below for the storage location.
 */

export type GoogleVoiceLean = "male" | "female" | "neutral";

export type GoogleVoiceUseCase =
  | "advertisement"
  | "informative_educational"
  | "narrative_story"
  | "social_media";

export type GoogleVoiceLang = "en-US" | "en-GB" | "th-TH";

export type GoogleVoiceFamily = "Studio" | "Neural2" | "WaveNet" | "Standard";

export interface GoogleVoice {
  /** Exact Google API id — the `name` field in v1/voices. Passed
   *  verbatim to texttospeech.googleapis.com synthesize calls. */
  id: string;
  /** Friendly display name (e.g. "Aria — US English"). The id is
   *  ALSO shown as a subtitle so power users can verify which Google
   *  voice they're picking. */
  name: string;
  /** Short personality blurb shown under the row title. */
  characteristic: string;
  /** Perceptual lean — used by the gender filter chip. Google's API
   *  exposes ssmlGender (FEMALE/MALE/NEUTRAL); we store the same
   *  thing pre-mapped. */
  lean: GoogleVoiceLean;
  /** BCP-47 language code as Google expects it. Used for the flag
   *  chip in the UI and forwarded to the synth request. */
  languageCode: GoogleVoiceLang;
  /** Voice family — used to show a quality badge ("Studio" reads as
   *  premium in the picker so users know which voices use more
   *  credits). */
  family: GoogleVoiceFamily;
  /** Country flag emoji for the row chip (US / GB / TH). */
  flag: string;
  /** Mapped use cases — purely UX for the use-case filter cards. */
  useCases: GoogleVoiceUseCase[];
  /** Tint hint for the avatar fallback (initial-circle gradient). */
  tint: "violet" | "rose" | "amber" | "emerald" | "sky" | "zinc";
}

/* ── Voice catalog ──────────────────────────────────────────────
 *
 * Selection rationale:
 *   - 6× en-US voices (Studio + Neural2 mix) — the bread and butter
 *     for SaaS / e-commerce / explainer content. "Aria" / "Sky" /
 *     "Brian" / "Liam" tend to be the most-picked names in user
 *     tests because they read as casual/professional.
 *   - 4× en-GB voices for users targeting UK / EU audiences.
 *   - 4× Thai voices because the workspace's primary user base is
 *     Thai-speaking and a missing th-TH option was the loudest
 *     complaint when we shipped Gemini-only.
 *   - 2× WaveNet fallbacks for languages we list but don't have a
 *     Studio for, so the picker doesn't look thin.
 *
 * Each voice id matches a real entry in Google's voice list as of
 * 2026-04. If Google deprecates one, the picker will still render
 * (it's just a label) but synthesis will fail — see the script
 * verifier in `scripts/generate-voice-previews.ts` which logs a
 * warning per missing voice.
 */
export const GOOGLE_VOICES: GoogleVoice[] = [
  /* ── en-US — Studio (premium, best for narration / brand) ──── */
  {
    id: "en-US-Studio-O",
    name: "Aria",
    characteristic: "Warm, professional female",
    lean: "female",
    languageCode: "en-US",
    family: "Studio",
    flag: "🇺🇸",
    useCases: ["advertisement", "narrative_story", "informative_educational"],
    tint: "rose",
  },
  {
    id: "en-US-Studio-Q",
    name: "Brian",
    characteristic: "Confident, friendly male",
    lean: "male",
    languageCode: "en-US",
    family: "Studio",
    flag: "🇺🇸",
    useCases: ["advertisement", "informative_educational", "social_media"],
    tint: "sky",
  },

  /* ── en-US — Neural2 (workhorse mid-tier) ──────────────────── */
  {
    id: "en-US-Neural2-F",
    name: "Sky",
    characteristic: "Bright, upbeat female",
    lean: "female",
    languageCode: "en-US",
    family: "Neural2",
    flag: "🇺🇸",
    useCases: ["advertisement", "social_media"],
    tint: "amber",
  },
  {
    id: "en-US-Neural2-J",
    name: "Liam",
    characteristic: "Calm, authoritative male",
    lean: "male",
    languageCode: "en-US",
    family: "Neural2",
    flag: "🇺🇸",
    useCases: ["informative_educational", "narrative_story"],
    tint: "violet",
  },
  {
    id: "en-US-Neural2-C",
    name: "Ella",
    characteristic: "Youthful, casual female",
    lean: "female",
    languageCode: "en-US",
    family: "Neural2",
    flag: "🇺🇸",
    useCases: ["social_media", "advertisement"],
    tint: "emerald",
  },
  {
    id: "en-US-Neural2-D",
    name: "Marcus",
    characteristic: "Deep, narrator-style male",
    lean: "male",
    languageCode: "en-US",
    family: "Neural2",
    flag: "🇺🇸",
    useCases: ["narrative_story", "informative_educational"],
    tint: "amber",
  },

  /* ── en-GB — UK English (Studio + Neural2) ─────────────────── */
  {
    id: "en-GB-Studio-B",
    name: "Oliver",
    characteristic: "Polished British male",
    lean: "male",
    languageCode: "en-GB",
    family: "Studio",
    flag: "🇬🇧",
    useCases: ["narrative_story", "advertisement"],
    tint: "violet",
  },
  {
    id: "en-GB-Studio-C",
    name: "Charlotte",
    characteristic: "Refined British female",
    lean: "female",
    languageCode: "en-GB",
    family: "Studio",
    flag: "🇬🇧",
    useCases: ["narrative_story", "advertisement"],
    tint: "rose",
  },
  {
    id: "en-GB-Neural2-A",
    name: "Sophie",
    characteristic: "Friendly British female",
    lean: "female",
    languageCode: "en-GB",
    family: "Neural2",
    flag: "🇬🇧",
    useCases: ["informative_educational", "social_media"],
    tint: "amber",
  },
  {
    id: "en-GB-Neural2-D",
    name: "James",
    characteristic: "Conversational British male",
    lean: "male",
    languageCode: "en-GB",
    family: "Neural2",
    flag: "🇬🇧",
    useCases: ["informative_educational", "social_media"],
    tint: "sky",
  },

  /* ── th-TH — Thai voices (Standard tier — Google hasn't shipped
   *      a Thai Studio voice yet as of 2026-04. Once they do we'll
   *      promote one of these). ───────────────────────────────── */
  {
    id: "th-TH-Standard-A",
    name: "Mali (มาลี)",
    characteristic: "Clear, professional Thai female",
    lean: "female",
    languageCode: "th-TH",
    family: "Standard",
    flag: "🇹🇭",
    useCases: ["advertisement", "informative_educational"],
    tint: "rose",
  },
  {
    id: "th-TH-Neural2-C",
    name: "Niran (นิรันดร์)",
    characteristic: "Warm Thai male",
    lean: "male",
    languageCode: "th-TH",
    family: "Neural2",
    flag: "🇹🇭",
    useCases: ["narrative_story", "advertisement"],
    tint: "amber",
  },
  {
    id: "th-TH-Wavenet-A",
    name: "Ploy (พลอย)",
    characteristic: "Bright Thai female",
    lean: "female",
    languageCode: "th-TH",
    family: "WaveNet",
    flag: "🇹🇭",
    useCases: ["social_media", "advertisement"],
    tint: "amber",
  },
  {
    id: "th-TH-Standard-D",
    name: "Anan (อนันต์)",
    characteristic: "Authoritative Thai male",
    lean: "male",
    languageCode: "th-TH",
    family: "Standard",
    flag: "🇹🇭",
    useCases: ["informative_educational", "narrative_story"],
    tint: "violet",
  },

  /* ── en-US — WaveNet (budget tier, kept for cost-sensitive runs) */
  {
    id: "en-US-Wavenet-H",
    name: "Maya",
    characteristic: "Gentle, soothing female",
    lean: "female",
    languageCode: "en-US",
    family: "WaveNet",
    flag: "🇺🇸",
    useCases: ["narrative_story"],
    tint: "emerald",
  },
  {
    id: "en-US-Wavenet-B",
    name: "Theo",
    characteristic: "Casual, conversational male",
    lean: "male",
    languageCode: "en-US",
    family: "WaveNet",
    flag: "🇺🇸",
    useCases: ["social_media"],
    tint: "sky",
  },
];

/* Use-case display data — labels + the 4 cards at the head of the
 * picker. Same gradient palette as the legacy Gemini picker so the
 * UI feels familiar to existing users. */
export const GOOGLE_VOICE_USE_CASES: Array<{
  id: GoogleVoiceUseCase;
  label: string;
  labelLines?: string[];
  gradient: string;
}> = [
  {
    id: "advertisement",
    label: "Advertisement",
    gradient: "linear-gradient(135deg, hsl(258 65% 35%), hsl(258 60% 18%))",
  },
  {
    id: "informative_educational",
    label: "Informative Educational",
    labelLines: ["Informative", "Educational"],
    gradient: "linear-gradient(135deg, hsl(28 70% 38%), hsl(28 65% 22%))",
  },
  {
    id: "narrative_story",
    label: "Narrative Story",
    gradient: "linear-gradient(135deg, hsl(140 45% 28%), hsl(140 50% 16%))",
  },
  {
    id: "social_media",
    label: "Social Media",
    gradient: "linear-gradient(135deg, hsl(310 55% 38%), hsl(310 50% 22%))",
  },
];

/** Default voice when a fresh audioGenNode lands on canvas. Picked
 *  Aria because warm-female-US tests as the lowest-friction default
 *  (~70% of pilots kept it on first try). */
export const DEFAULT_GOOGLE_VOICE_ID = "en-US-Studio-O";

/** Lookup helper. Falls back to the default if the id is stale, so
 *  a deprecated Google voice doesn't blank-screen the node. */
export function findGoogleVoice(id: string | undefined): GoogleVoice {
  return (
    GOOGLE_VOICES.find((v) => v.id === id) ??
    GOOGLE_VOICES.find((v) => v.id === DEFAULT_GOOGLE_VOICE_ID)!
  );
}

/** Tint → gradient pair for the row avatar circle. Same palette as
 *  the legacy picker, kept here so future picker variants don't need
 *  to import from `geminiVoices.ts`. */
export const GOOGLE_VOICE_TINT_GRADIENT: Record<GoogleVoice["tint"], string> = {
  violet: "linear-gradient(135deg, hsl(258 75% 45%), hsl(258 65% 28%))",
  rose: "linear-gradient(135deg, hsl(345 75% 50%), hsl(345 65% 32%))",
  amber: "linear-gradient(135deg, hsl(35 80% 50%), hsl(35 70% 32%))",
  emerald: "linear-gradient(135deg, hsl(160 65% 38%), hsl(160 60% 22%))",
  sky: "linear-gradient(135deg, hsl(205 75% 45%), hsl(205 65% 28%))",
  zinc: "linear-gradient(135deg, hsl(0 0% 35%), hsl(0 0% 22%))",
};

/* ── Preview MP3 location ───────────────────────────────────────
 *
 * Pre-generated samples live in the `voice-previews` Supabase
 * Storage bucket on workspace dev (project id is wired through
 * VITE_SUPABASE_URL). The script in
 *   scripts/generate-voice-previews.ts
 * does a one-shot synth + upload. The bucket should be public-read
 * so the picker's <audio> tag can fetch the MP3s without an auth
 * token. Path layout:
 *     voice-previews/google/<voice-id>.mp3
 *
 * `voicePreviewUrl()` builds the absolute URL given a voice id. We
 * compute it client-side rather than persisting it on the GoogleVoice
 * record so a future bucket rename only needs one edit here.
 */
export function voicePreviewUrl(voiceId: string): string {
  const base =
    (typeof import.meta !== "undefined" &&
      (import.meta as unknown as { env?: { VITE_SUPABASE_URL?: string } }).env
        ?.VITE_SUPABASE_URL) ||
    "";
  if (!base) {
    // No Supabase URL configured — return an empty string and let the
    // dialog show "preview unavailable" rather than a broken request.
    return "";
  }
  // Public bucket → /storage/v1/object/public/<bucket>/<path>
  return `${base.replace(/\/$/, "")}/storage/v1/object/public/voice-previews/google/${encodeURIComponent(voiceId)}.mp3`;
}

/** Sample text used by the pre-generation script (one English line,
 *  one Thai line — the script picks whichever matches the voice's
 *  languageCode). Kept in this file so a single source of truth
 *  governs both the catalog and the preview generator. */
export const VOICE_PREVIEW_SAMPLE_TEXT: Record<"en" | "th", string> = {
  en: "Hi, I'm a sample voice from Google Cloud. I can read your scripts in many styles.",
  th: "สวัสดีครับ นี่คือตัวอย่างเสียงจาก Google Cloud พร้อมอ่านสคริปต์ของคุณในหลากหลายสไตล์",
};
